import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { Suspense } from 'react';
import Footer from './components/Footer';
import Header from './components/Header';
import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'], preload: true, display: 'swap' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
    params: Promise<{ user: object }>;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className} antialiased`}>
                <SessionProvider>
                    <Suspense fallback={<div>Loading...</div>}>
                        <Header />
                        <main> {children}</main>
                    </Suspense>
                    <Footer />
                </SessionProvider>
            </body>
        </html>
    );
}
