import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import Link from "../../node_modules/next/link";
import Header from './components/Header';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="py-4 px-6 @container/main justify-center border-2 border-red-500 m-2"> */}
        <Header />
        {children}
        <footer className="container py-8 text-gray-500 mx-auto">
          Job Board &copy; 2025 - All rights reserved
        </footer>
        {/* </div> */}
      </body>
    </html>
  );
}
